-----------------------------------------------------------------------------
INSERT INTO COMMON_NAME(NAME) VALUES('Villous waterclover');
INSERT INTO COMMON_NAME(NAME) VALUES('Yellow Hibiscus');
INSERT INTO COMMON_NAME(NAME) VALUES('White Kauai Rosemallow');
INSERT INTO COMMON_NAME(NAME) VALUES('Black-fruited Coprosma');
INSERT INTO COMMON_NAME(NAME) VALUES('Oceanblue Morning Glory');
INSERT INTO COMMON_NAME(NAME) VALUES('Cat\'s claw');
INSERT INTO COMMON_NAME(NAME) VALUES('Dune Tetramolopium');
INSERT INTO COMMON_NAME(NAME) VALUES('Indian Tulip Tree');
INSERT INTO COMMON_NAME(NAME) VALUES('Mexican Primrose Willow');
-----------------------------------------------------------------------------