-----------------------------------------------------------------------------
CREATE PROCEDURE PROCEDURE_CREATE_SUBMISSION(@USERID INT, @SPECIES_NAME VARCHAR(MAX), @SUBSPECIES_NAME VARCHAR(MAX), @REPORT TEXT, @DATE DATETIME, @COORDINATE GEOGRAPHY, @ISLAND_NAME VARCHAR(MAX))
AS
BEGIN
    DECLARE @ret AS INT;
        SET @ret = 0;

    DECLARE @SPECIES_ID AS INT;
        SET @SPECIES_ID = (SELECT [dbo].FUNCTION_SPECIES_ID(@SPECIES_NAME, @SUBSPECIES_NAME));
    
    DECLARE @SUBMISSION AS TABLE(ID INT);
    DECLARE @SUBMISSION_ID AS INT;
        SET @SUBMISSION_ID = -1;

    BEGIN TRY
        INSERT INTO SUBMISSION([DATE], REPORT, [USER_ID], SPECIES_ID)
            OUTPUT INSERTED.ID
                INTO @SUBMISSION
            VALUES(@DATE, @REPORT, @USERID, @SPECIES_ID);
        
        SET @SUBMISSION_ID = (SELECT CONVERT(INT, (SELECT TOP 1 ID FROM @SUBMISSION)) AS INT);

        INSERT INTO GEOLOCATION(COORDINATE, SUBMISSION_ID, ISLAND_ID)
            VALUES(@COORDINATE, @SUBMISSION_ID, (SELECT [dbo].FUNCTION_ISLAND_ID(@ISLAND_NAME)));
        SET @ret = 1;
    END TRY
    BEGIN CATCH
        SET @ret = 0;
    END CATCH

    RETURN @ret;
END;
GO
-----------------------------------------------------------------------------
